stages:
  default-pop:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default POP
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-POP

  default-bias:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BIAS
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-BIAS
      - recs/${item}-default-BIAS

  default-emf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default E-MF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-E-MF
      - recs/${item}-default-E-MF
  
  default-imf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default I-MF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-I-MF
  
  default-lift:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default LIFT
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-LIFT

  default-torchmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchMF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-TorchMF
      - recs/${item}-default-TorchMF

  default-user-imf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default UserIMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-UserIMF

  default-user-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default UserLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-UserLMF

  default-samp-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default SampLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-SampLMF

  default-bpr:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BPR
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-BPR

  default-tag-emf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default --tags data/${item} TagEMF
      deps:
      - data/${item}-split
      - data/${item}
      outs:
      - preds/${item}-default-TagEMF
      - recs/${item}-default-TagEMF
