stages:
  run-pop:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item} POP
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-POP

  run-bias:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item} BIAS
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-BIAS
      - recs/${item}-BIAS

  run-emf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item} E-MF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-E-MF
      - recs/${item}-E-MF
  
  run-imf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item} I-MF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-I-MF
  
  run-lift:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item} LIFT
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-LIFT