stages:
  default-pop:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default POP
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-POP

  default-bias:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BIAS
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-BIAS
      - recs/${item}-BIAS

  default-emf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default E-MF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-E-MF
      - recs/${item}-E-MF
  
  default-imf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default I-MF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-I-MF
  
  default-lift:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default LIFT
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-LIFT

  default-torchmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchMF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-TorchMF
      - recs/${item}-TorchMF

  default-imf1:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchIMF1
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-TorchIMF1

  default-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-TorchLMF
    
  default-samp-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default SampLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-SampLMF
  
  default-bpr:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BPR
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-BPR