stages:
  default-pop:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default POP
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-POP

  default-bias:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BIAS
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-BIAS
      - recs/${item}-default-BIAS

  default-emf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default E-MF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-E-MF
      - recs/${item}-default-E-MF
  
  default-imf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default I-MF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-I-MF
  
  default-lift:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default LIFT
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-LIFT

  default-torchmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchMF
      deps:
      - data/${item}-split
      outs:
      - preds/${item}-default-TorchMF
      - recs/${item}-default-TorchMF

  default-imf1:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchIMF1
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-TorchIMF1

  default-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default TorchLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-TorchLMF
    
  default-samp-lmf:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default SampLMF
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-SampLMF
  
  default-bpr:
    foreach:
    - ml-latest-small
    - ml-20m
    do:
      cmd: python run-algo.py -d data/${item}-split -p ${item}-default BPR
      deps:
      - data/${item}-split
      outs:
      - recs/${item}-default-BPR